# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MonkeyDevTestDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MonkeyDevTestDemo

end


source 'https://github.com/AloneMonkey/MonkeyDevSpecs.git'

target 'MonkeyDevTestDemoDylib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'MDSettingCenter'

end
